name: Docker Image CI

on:
  push:
    branches: [master]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Images Build And Push
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        # Docker Registry Url, eg: registry.xxxxx.cs.com
        registry_url: https://hub.docker.com
        namespace: pavankrish
        # Docker Image Repository Name, eg: adc.ms.eureka
        repository_name: myhelmkubeimage
        # Docker Login UserName, from: https://cr.console..com/
        user_name: pavankrish
        # Docker Login Password, from: https://cr.console..com/
        password: Vamsi@1988
        # Image Build Version
        image_version: latest
